[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
flare_coston = "https://coston-api.flare.network/ext/bc/C/rpc"
flare_mainnet = "https://flare-api.flare.network/ext/bc/C/rpc"
local = "http://localhost:8545"

[etherscan]
flare = { key = "${FLARE_ETHERSCAN_KEY}" }
